name: base-publish

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile_base'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Dockerfile changes
        id: dockerfile-changed
        run: |
          git diff --quiet HEAD^ -- Dockerfile || echo "::set-output name=changed::true"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ubuntu
        if: steps.dockerfile-changed.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile_base
          push: true
          tags: maxzhang666/ubuntu_chronocat
